// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: compass/iam/token.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Compass.Iam {

  /// <summary>Holder for reflection information generated from compass/iam/token.proto</summary>
  public static partial class TokenReflection {

    #region Descriptor
    /// <summary>File descriptor for compass/iam/token.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TokenReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdjb21wYXNzL2lhbS90b2tlbi5wcm90bxILY29tcGFzcy5pYW0aHmdvb2ds",
            "ZS9wcm90b2J1Zi93cmFwcGVycy5wcm90bxoaY29tcGFzcy90eXBlL2dlby9n",
            "ZW8ucHJvdG8i4AEKBVRva2VuEiwKB3VzZXJfaWQYASABKAsyGy5nb29nbGUu",
            "cHJvdG9idWYuSW50NjRWYWx1ZRIUCgx3b3Jrc3BhY2VfaWQYAiABKAMSDQoF",
            "ZW1haWwYAyABKAkSEQoJd29ya3NwYWNlGAQgASgJEg0KBWFkbWluGAUgASgI",
            "EioKCGdlb2ZlbmNlGAYgASgLMhguY29tcGFzcy50eXBlLmdlby5SZWdpb24S",
            "KAoEaG9tZRgHIAEoCzIaLmNvbXBhc3MudHlwZS5nZW8uTGF0TG5nMzISDAoE",
            "dmlucxgIIAMoCUI3WjV2Mi5jb21wYXNzLmlvdC9nZW5wcm90by9jb21wYXNz",
            "YXBpcy9jb21wYXNzL2lhbTtpYW1wYmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Compass.Type.Geo.GeoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Compass.Iam.Token), global::Compass.Iam.Token.Parser, new[]{ "UserId", "WorkspaceId", "Email", "Workspace", "Admin", "Geofence", "Home", "Vins" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Token : pb::IMessage<Token>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Token> _parser = new pb::MessageParser<Token>(() => new Token());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Token> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Compass.Iam.TokenReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Token() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Token(Token other) : this() {
      UserId = other.UserId;
      workspaceId_ = other.workspaceId_;
      email_ = other.email_;
      workspace_ = other.workspace_;
      admin_ = other.admin_;
      geofence_ = other.geofence_ != null ? other.geofence_.Clone() : null;
      home_ = other.home_ != null ? other.home_.Clone() : null;
      vins_ = other.vins_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Token Clone() {
      return new Token(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private static readonly pb::FieldCodec<long?> _single_userId_codec = pb::FieldCodec.ForStructWrapper<long>(10);
    private long? userId_;
    /// <summary>
    /// if user_id is null, token is a workspace token and email should be null
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long? UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }


    /// <summary>Field number for the "workspace_id" field.</summary>
    public const int WorkspaceIdFieldNumber = 2;
    private long workspaceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long WorkspaceId {
      get { return workspaceId_; }
      set {
        workspaceId_ = value;
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 3;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "workspace" field.</summary>
    public const int WorkspaceFieldNumber = 4;
    private string workspace_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Workspace {
      get { return workspace_; }
      set {
        workspace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "admin" field.</summary>
    public const int AdminFieldNumber = 5;
    private bool admin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Admin {
      get { return admin_; }
      set {
        admin_ = value;
      }
    }

    /// <summary>Field number for the "geofence" field.</summary>
    public const int GeofenceFieldNumber = 6;
    private global::Compass.Type.Geo.Region geofence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Compass.Type.Geo.Region Geofence {
      get { return geofence_; }
      set {
        geofence_ = value;
      }
    }

    /// <summary>Field number for the "home" field.</summary>
    public const int HomeFieldNumber = 7;
    private global::Compass.Type.Geo.LatLng32 home_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Compass.Type.Geo.LatLng32 Home {
      get { return home_; }
      set {
        home_ = value;
      }
    }

    /// <summary>Field number for the "vins" field.</summary>
    public const int VinsFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_vins_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> vins_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Vins {
      get { return vins_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Token);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Token other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (WorkspaceId != other.WorkspaceId) return false;
      if (Email != other.Email) return false;
      if (Workspace != other.Workspace) return false;
      if (Admin != other.Admin) return false;
      if (!object.Equals(Geofence, other.Geofence)) return false;
      if (!object.Equals(Home, other.Home)) return false;
      if(!vins_.Equals(other.vins_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (userId_ != null) hash ^= UserId.GetHashCode();
      if (WorkspaceId != 0L) hash ^= WorkspaceId.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Workspace.Length != 0) hash ^= Workspace.GetHashCode();
      if (Admin != false) hash ^= Admin.GetHashCode();
      if (geofence_ != null) hash ^= Geofence.GetHashCode();
      if (home_ != null) hash ^= Home.GetHashCode();
      hash ^= vins_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (userId_ != null) {
        _single_userId_codec.WriteTagAndValue(output, UserId);
      }
      if (WorkspaceId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(WorkspaceId);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (Workspace.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Workspace);
      }
      if (Admin != false) {
        output.WriteRawTag(40);
        output.WriteBool(Admin);
      }
      if (geofence_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Geofence);
      }
      if (home_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Home);
      }
      vins_.WriteTo(output, _repeated_vins_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (userId_ != null) {
        _single_userId_codec.WriteTagAndValue(ref output, UserId);
      }
      if (WorkspaceId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(WorkspaceId);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (Workspace.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Workspace);
      }
      if (Admin != false) {
        output.WriteRawTag(40);
        output.WriteBool(Admin);
      }
      if (geofence_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Geofence);
      }
      if (home_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Home);
      }
      vins_.WriteTo(ref output, _repeated_vins_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (userId_ != null) {
        size += _single_userId_codec.CalculateSizeWithTag(UserId);
      }
      if (WorkspaceId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(WorkspaceId);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Workspace.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Workspace);
      }
      if (Admin != false) {
        size += 1 + 1;
      }
      if (geofence_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Geofence);
      }
      if (home_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Home);
      }
      size += vins_.CalculateSize(_repeated_vins_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Token other) {
      if (other == null) {
        return;
      }
      if (other.userId_ != null) {
        if (userId_ == null || other.UserId != 0L) {
          UserId = other.UserId;
        }
      }
      if (other.WorkspaceId != 0L) {
        WorkspaceId = other.WorkspaceId;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Workspace.Length != 0) {
        Workspace = other.Workspace;
      }
      if (other.Admin != false) {
        Admin = other.Admin;
      }
      if (other.geofence_ != null) {
        if (geofence_ == null) {
          Geofence = new global::Compass.Type.Geo.Region();
        }
        Geofence.MergeFrom(other.Geofence);
      }
      if (other.home_ != null) {
        if (home_ == null) {
          Home = new global::Compass.Type.Geo.LatLng32();
        }
        Home.MergeFrom(other.Home);
      }
      vins_.Add(other.vins_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            long? value = _single_userId_codec.Read(input);
            if (userId_ == null || value != 0L) {
              UserId = value;
            }
            break;
          }
          case 16: {
            WorkspaceId = input.ReadInt64();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            Workspace = input.ReadString();
            break;
          }
          case 40: {
            Admin = input.ReadBool();
            break;
          }
          case 50: {
            if (geofence_ == null) {
              Geofence = new global::Compass.Type.Geo.Region();
            }
            input.ReadMessage(Geofence);
            break;
          }
          case 58: {
            if (home_ == null) {
              Home = new global::Compass.Type.Geo.LatLng32();
            }
            input.ReadMessage(Home);
            break;
          }
          case 66: {
            vins_.AddEntriesFrom(input, _repeated_vins_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            long? value = _single_userId_codec.Read(ref input);
            if (userId_ == null || value != 0L) {
              UserId = value;
            }
            break;
          }
          case 16: {
            WorkspaceId = input.ReadInt64();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            Workspace = input.ReadString();
            break;
          }
          case 40: {
            Admin = input.ReadBool();
            break;
          }
          case 50: {
            if (geofence_ == null) {
              Geofence = new global::Compass.Type.Geo.Region();
            }
            input.ReadMessage(Geofence);
            break;
          }
          case 58: {
            if (home_ == null) {
              Home = new global::Compass.Type.Geo.LatLng32();
            }
            input.ReadMessage(Home);
            break;
          }
          case 66: {
            vins_.AddEntriesFrom(ref input, _repeated_vins_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
