# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compass/iam/permission.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ompass/iam/permission.proto\x12\x0b\x63ompass.iam\x1a google/protobuf/descriptor.proto\"\x1a\n\nPermission\x12\x0c\n\x04name\x18\x01 \x01(\t:M\n\npermission\x12\x1e.google.protobuf.MethodOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x17.compass.iam.PermissionB7Z5v2.compass.iot/genproto/compassapis/compass/iam;iampbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compass.iam.permission_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(permission)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5v2.compass.iot/genproto/compassapis/compass/iam;iampb'
  _PERMISSION._serialized_start=79
  _PERMISSION._serialized_end=105
# @@protoc_insertion_point(module_scope)
