# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compass/iam/token.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from compass.type.geo import geo_pb2 as compass_dot_type_dot_geo_dot_geo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ompass/iam/token.proto\x12\x0b\x63ompass.iam\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1a\x63ompass/type/geo/geo.proto\"\xd2\x01\n\x05Token\x12,\n\x07user_id\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x14\n\x0cworkspace_id\x18\x02 \x01(\x03\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\tworkspace\x18\x04 \x01(\t\x12\r\n\x05\x61\x64min\x18\x05 \x01(\x08\x12*\n\x08geofence\x18\x06 \x01(\x0b\x32\x18.compass.type.geo.Region\x12(\n\x04home\x18\x07 \x01(\x0b\x32\x1a.compass.type.geo.LatLng32B7Z5v2.compass.iot/genproto/compassapis/compass/iam;iampbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compass.iam.token_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5v2.compass.iot/genproto/compassapis/compass/iam;iampb'
  _TOKEN._serialized_start=101
  _TOKEN._serialized_end=311
# @@protoc_insertion_point(module_scope)
