// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: compass/harvest/v1alpha1/harvest.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Compass.Harvest.V1alpha1 {
  public static partial class IngestService
  {
    static readonly string __ServiceName = "compass.harvest.v1alpha1.IngestService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PositionEvent> __Marshaller_compassiot_compass_v1_PositionEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PositionEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.Vehicle> __Marshaller_compassiot_compass_v1_Vehicle = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.Vehicle.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.PositionEventCompat> __Marshaller_compass_harvest_v1alpha1_PositionEventCompat = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.PositionEventCompat.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.BatchInsertRequest> __Marshaller_compass_harvest_v1alpha1_BatchInsertRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.BatchInsertRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.BatchInsertResponse> __Marshaller_compass_harvest_v1alpha1_BatchInsertResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.BatchInsertResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest> __Marshaller_compass_harvest_v1alpha1_BatchInsertCompatRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Insert = new grpc::Method<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Insert",
        __Marshaller_compassiot_compass_v1_PositionEvent,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartial = new grpc::Method<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartial",
        __Marshaller_compassiot_compass_v1_PositionEvent,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.Vehicle, global::Google.Protobuf.WellKnownTypes.Empty> __Method_PutVehicle = new grpc::Method<global::Compassiot.Compass.V1.Vehicle, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PutVehicle",
        __Marshaller_compassiot_compass_v1_Vehicle,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compass.Harvest.V1alpha1.PositionEventCompat, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertCompat = new grpc::Method<global::Compass.Harvest.V1alpha1.PositionEventCompat, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertCompat",
        __Marshaller_compass_harvest_v1alpha1_PositionEventCompat,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse> __Method_BatchInsert = new grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BatchInsert",
        __Marshaller_compass_harvest_v1alpha1_BatchInsertRequest,
        __Marshaller_compass_harvest_v1alpha1_BatchInsertResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse> __Method_BatchInsertPartial = new grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BatchInsertPartial",
        __Marshaller_compass_harvest_v1alpha1_BatchInsertRequest,
        __Marshaller_compass_harvest_v1alpha1_BatchInsertResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse> __Method_BatchInsertCompat = new grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BatchInsertCompat",
        __Marshaller_compass_harvest_v1alpha1_BatchInsertCompatRequest,
        __Marshaller_compass_harvest_v1alpha1_BatchInsertResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Compass.Harvest.V1alpha1.HarvestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of IngestService</summary>
    [grpc::BindServiceMethod(typeof(IngestService), "BindService")]
    public abstract partial class IngestServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Insert(global::Compassiot.Compass.V1.PositionEvent request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartial(global::Compassiot.Compass.V1.PositionEvent request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> PutVehicle(global::Compassiot.Compass.V1.Vehicle request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertCompat(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsert(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertPartial(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertCompat(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for IngestService</summary>
    public partial class IngestServiceClient : grpc::ClientBase<IngestServiceClient>
    {
      /// <summary>Creates a new client for IngestService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public IngestServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IngestService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public IngestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected IngestServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected IngestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Insert(global::Compassiot.Compass.V1.PositionEvent request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Insert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Insert(global::Compassiot.Compass.V1.PositionEvent request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Insert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertAsync(global::Compassiot.Compass.V1.PositionEvent request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertAsync(global::Compassiot.Compass.V1.PositionEvent request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Insert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartial(global::Compassiot.Compass.V1.PositionEvent request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartial(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartial(global::Compassiot.Compass.V1.PositionEvent request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartial, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialAsync(global::Compassiot.Compass.V1.PositionEvent request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialAsync(global::Compassiot.Compass.V1.PositionEvent request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartial, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty PutVehicle(global::Compassiot.Compass.V1.Vehicle request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PutVehicle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty PutVehicle(global::Compassiot.Compass.V1.Vehicle request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PutVehicle, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> PutVehicleAsync(global::Compassiot.Compass.V1.Vehicle request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PutVehicleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> PutVehicleAsync(global::Compassiot.Compass.V1.Vehicle request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PutVehicle, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertCompat(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertCompat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertCompat(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertCompat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertCompatAsync(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertCompatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertCompatAsync(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertCompat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsert(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsert(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BatchInsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertAsync(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertAsync(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BatchInsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsertPartial(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertPartial(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsertPartial(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BatchInsertPartial, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertPartialAsync(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertPartialAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertPartialAsync(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BatchInsertPartial, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsertCompat(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertCompat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsertCompat(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BatchInsertCompat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertCompatAsync(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertCompatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertCompatAsync(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BatchInsertCompat, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override IngestServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IngestServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(IngestServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Insert, serviceImpl.Insert)
          .AddMethod(__Method_InsertPartial, serviceImpl.InsertPartial)
          .AddMethod(__Method_PutVehicle, serviceImpl.PutVehicle)
          .AddMethod(__Method_InsertCompat, serviceImpl.InsertCompat)
          .AddMethod(__Method_BatchInsert, serviceImpl.BatchInsert)
          .AddMethod(__Method_BatchInsertPartial, serviceImpl.BatchInsertPartial)
          .AddMethod(__Method_BatchInsertCompat, serviceImpl.BatchInsertCompat).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, IngestServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Insert, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Insert));
      serviceBinder.AddMethod(__Method_InsertPartial, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartial));
      serviceBinder.AddMethod(__Method_PutVehicle, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.Vehicle, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.PutVehicle));
      serviceBinder.AddMethod(__Method_InsertCompat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compass.Harvest.V1alpha1.PositionEventCompat, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertCompat));
      serviceBinder.AddMethod(__Method_BatchInsert, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(serviceImpl.BatchInsert));
      serviceBinder.AddMethod(__Method_BatchInsertPartial, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(serviceImpl.BatchInsertPartial));
      serviceBinder.AddMethod(__Method_BatchInsertCompat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(serviceImpl.BatchInsertCompat));
    }

  }
}
#endregion
