// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: compass/harvest/v1alpha1/harvest.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Compass.Harvest.V1alpha1 {
  public static partial class IngestService
  {
    static readonly string __ServiceName = "compass.harvest.v1alpha1.IngestService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PositionEvent> __Marshaller_compassiot_compass_v1_PositionEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PositionEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.PositionEventCompat> __Marshaller_compass_harvest_v1alpha1_PositionEventCompat = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.PositionEventCompat.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventLatLng> __Marshaller_compassiot_compass_v1_PartialEventLatLng = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventLatLng.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventSpeed> __Marshaller_compassiot_compass_v1_PartialEventSpeed = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventSpeed.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventAcceleration> __Marshaller_compassiot_compass_v1_PartialEventAcceleration = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventAcceleration.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventGyro> __Marshaller_compassiot_compass_v1_PartialEventGyro = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventGyro.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventOdo> __Marshaller_compassiot_compass_v1_PartialEventOdo = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventOdo.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventFuelOrCharge> __Marshaller_compassiot_compass_v1_PartialEventFuelOrCharge = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventFuelOrCharge.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventMetadataKV> __Marshaller_compassiot_compass_v1_PartialEventMetadataKV = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventMetadataKV.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialEventMetadataJSON> __Marshaller_compassiot_compass_v1_PartialEventMetadataJSON = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialEventMetadataJSON.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialVehicleMetadataKV> __Marshaller_compassiot_compass_v1_PartialVehicleMetadataKV = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialVehicleMetadataKV.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compassiot.Compass.V1.PartialVehicleMetadataJSON> __Marshaller_compassiot_compass_v1_PartialVehicleMetadataJSON = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compassiot.Compass.V1.PartialVehicleMetadataJSON.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.BatchInsertRequest> __Marshaller_compass_harvest_v1alpha1_BatchInsertRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.BatchInsertRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.BatchInsertResponse> __Marshaller_compass_harvest_v1alpha1_BatchInsertResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.BatchInsertResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest> __Marshaller_compass_harvest_v1alpha1_BatchInsertCompatRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Insert = new grpc::Method<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Insert",
        __Marshaller_compassiot_compass_v1_PositionEvent,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compass.Harvest.V1alpha1.PositionEventCompat, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertCompat = new grpc::Method<global::Compass.Harvest.V1alpha1.PositionEventCompat, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertCompat",
        __Marshaller_compass_harvest_v1alpha1_PositionEventCompat,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventLatLng, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialLatLng = new grpc::Method<global::Compassiot.Compass.V1.PartialEventLatLng, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialLatLng",
        __Marshaller_compassiot_compass_v1_PartialEventLatLng,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventSpeed, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialSpeed = new grpc::Method<global::Compassiot.Compass.V1.PartialEventSpeed, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialSpeed",
        __Marshaller_compassiot_compass_v1_PartialEventSpeed,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventAcceleration, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialEventAcceleration = new grpc::Method<global::Compassiot.Compass.V1.PartialEventAcceleration, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialEventAcceleration",
        __Marshaller_compassiot_compass_v1_PartialEventAcceleration,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventGyro, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialEventGyro = new grpc::Method<global::Compassiot.Compass.V1.PartialEventGyro, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialEventGyro",
        __Marshaller_compassiot_compass_v1_PartialEventGyro,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventOdo, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialEventOdo = new grpc::Method<global::Compassiot.Compass.V1.PartialEventOdo, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialEventOdo",
        __Marshaller_compassiot_compass_v1_PartialEventOdo,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventFuelOrCharge, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialEventFuelOrCharge = new grpc::Method<global::Compassiot.Compass.V1.PartialEventFuelOrCharge, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialEventFuelOrCharge",
        __Marshaller_compassiot_compass_v1_PartialEventFuelOrCharge,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventMetadataKV, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialEventMetadataKV = new grpc::Method<global::Compassiot.Compass.V1.PartialEventMetadataKV, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialEventMetadataKV",
        __Marshaller_compassiot_compass_v1_PartialEventMetadataKV,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialEventMetadataJSON, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialEventMetadataJSON = new grpc::Method<global::Compassiot.Compass.V1.PartialEventMetadataJSON, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialEventMetadataJSON",
        __Marshaller_compassiot_compass_v1_PartialEventMetadataJSON,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialVehicleMetadataKV, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialVehicleMetadataKV = new grpc::Method<global::Compassiot.Compass.V1.PartialVehicleMetadataKV, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialVehicleMetadataKV",
        __Marshaller_compassiot_compass_v1_PartialVehicleMetadataKV,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compassiot.Compass.V1.PartialVehicleMetadataJSON, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InsertPartialVehicleMetadataJSON = new grpc::Method<global::Compassiot.Compass.V1.PartialVehicleMetadataJSON, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertPartialVehicleMetadataJSON",
        __Marshaller_compassiot_compass_v1_PartialVehicleMetadataJSON,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse> __Method_BatchInsert = new grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BatchInsert",
        __Marshaller_compass_harvest_v1alpha1_BatchInsertRequest,
        __Marshaller_compass_harvest_v1alpha1_BatchInsertResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse> __Method_BatchInsertCompat = new grpc::Method<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BatchInsertCompat",
        __Marshaller_compass_harvest_v1alpha1_BatchInsertCompatRequest,
        __Marshaller_compass_harvest_v1alpha1_BatchInsertResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Compass.Harvest.V1alpha1.HarvestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of IngestService</summary>
    [grpc::BindServiceMethod(typeof(IngestService), "BindService")]
    public abstract partial class IngestServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> Insert(global::Compassiot.Compass.V1.PositionEvent request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertCompat(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialLatLng(global::Compassiot.Compass.V1.PartialEventLatLng request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialSpeed(global::Compassiot.Compass.V1.PartialEventSpeed request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventAcceleration(global::Compassiot.Compass.V1.PartialEventAcceleration request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventGyro(global::Compassiot.Compass.V1.PartialEventGyro request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventOdo(global::Compassiot.Compass.V1.PartialEventOdo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventFuelOrCharge(global::Compassiot.Compass.V1.PartialEventFuelOrCharge request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventMetadataKV(global::Compassiot.Compass.V1.PartialEventMetadataKV request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventMetadataJSON(global::Compassiot.Compass.V1.PartialEventMetadataJSON request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialVehicleMetadataKV(global::Compassiot.Compass.V1.PartialVehicleMetadataKV request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialVehicleMetadataJSON(global::Compassiot.Compass.V1.PartialVehicleMetadataJSON request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsert(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertCompat(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for IngestService</summary>
    public partial class IngestServiceClient : grpc::ClientBase<IngestServiceClient>
    {
      /// <summary>Creates a new client for IngestService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public IngestServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IngestService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public IngestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected IngestServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected IngestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Insert(global::Compassiot.Compass.V1.PositionEvent request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Insert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty Insert(global::Compassiot.Compass.V1.PositionEvent request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Insert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertAsync(global::Compassiot.Compass.V1.PositionEvent request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertAsync(global::Compassiot.Compass.V1.PositionEvent request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Insert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertCompat(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertCompat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertCompat(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertCompat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertCompatAsync(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertCompatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertCompatAsync(global::Compass.Harvest.V1alpha1.PositionEventCompat request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertCompat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialLatLng(global::Compassiot.Compass.V1.PartialEventLatLng request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialLatLng(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialLatLng(global::Compassiot.Compass.V1.PartialEventLatLng request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialLatLng, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialLatLngAsync(global::Compassiot.Compass.V1.PartialEventLatLng request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialLatLngAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialLatLngAsync(global::Compassiot.Compass.V1.PartialEventLatLng request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialLatLng, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialSpeed(global::Compassiot.Compass.V1.PartialEventSpeed request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialSpeed(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialSpeed(global::Compassiot.Compass.V1.PartialEventSpeed request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialSpeed, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialSpeedAsync(global::Compassiot.Compass.V1.PartialEventSpeed request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialSpeedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialSpeedAsync(global::Compassiot.Compass.V1.PartialEventSpeed request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialSpeed, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventAcceleration(global::Compassiot.Compass.V1.PartialEventAcceleration request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventAcceleration(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventAcceleration(global::Compassiot.Compass.V1.PartialEventAcceleration request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialEventAcceleration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventAccelerationAsync(global::Compassiot.Compass.V1.PartialEventAcceleration request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventAccelerationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventAccelerationAsync(global::Compassiot.Compass.V1.PartialEventAcceleration request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialEventAcceleration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventGyro(global::Compassiot.Compass.V1.PartialEventGyro request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventGyro(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventGyro(global::Compassiot.Compass.V1.PartialEventGyro request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialEventGyro, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventGyroAsync(global::Compassiot.Compass.V1.PartialEventGyro request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventGyroAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventGyroAsync(global::Compassiot.Compass.V1.PartialEventGyro request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialEventGyro, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventOdo(global::Compassiot.Compass.V1.PartialEventOdo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventOdo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventOdo(global::Compassiot.Compass.V1.PartialEventOdo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialEventOdo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventOdoAsync(global::Compassiot.Compass.V1.PartialEventOdo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventOdoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventOdoAsync(global::Compassiot.Compass.V1.PartialEventOdo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialEventOdo, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventFuelOrCharge(global::Compassiot.Compass.V1.PartialEventFuelOrCharge request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventFuelOrCharge(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventFuelOrCharge(global::Compassiot.Compass.V1.PartialEventFuelOrCharge request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialEventFuelOrCharge, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventFuelOrChargeAsync(global::Compassiot.Compass.V1.PartialEventFuelOrCharge request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventFuelOrChargeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventFuelOrChargeAsync(global::Compassiot.Compass.V1.PartialEventFuelOrCharge request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialEventFuelOrCharge, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventMetadataKV(global::Compassiot.Compass.V1.PartialEventMetadataKV request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventMetadataKV(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventMetadataKV(global::Compassiot.Compass.V1.PartialEventMetadataKV request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialEventMetadataKV, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventMetadataKVAsync(global::Compassiot.Compass.V1.PartialEventMetadataKV request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventMetadataKVAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventMetadataKVAsync(global::Compassiot.Compass.V1.PartialEventMetadataKV request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialEventMetadataKV, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventMetadataJSON(global::Compassiot.Compass.V1.PartialEventMetadataJSON request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventMetadataJSON(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialEventMetadataJSON(global::Compassiot.Compass.V1.PartialEventMetadataJSON request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialEventMetadataJSON, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventMetadataJSONAsync(global::Compassiot.Compass.V1.PartialEventMetadataJSON request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialEventMetadataJSONAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialEventMetadataJSONAsync(global::Compassiot.Compass.V1.PartialEventMetadataJSON request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialEventMetadataJSON, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialVehicleMetadataKV(global::Compassiot.Compass.V1.PartialVehicleMetadataKV request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialVehicleMetadataKV(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialVehicleMetadataKV(global::Compassiot.Compass.V1.PartialVehicleMetadataKV request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialVehicleMetadataKV, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialVehicleMetadataKVAsync(global::Compassiot.Compass.V1.PartialVehicleMetadataKV request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialVehicleMetadataKVAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialVehicleMetadataKVAsync(global::Compassiot.Compass.V1.PartialVehicleMetadataKV request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialVehicleMetadataKV, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialVehicleMetadataJSON(global::Compassiot.Compass.V1.PartialVehicleMetadataJSON request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialVehicleMetadataJSON(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InsertPartialVehicleMetadataJSON(global::Compassiot.Compass.V1.PartialVehicleMetadataJSON request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPartialVehicleMetadataJSON, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialVehicleMetadataJSONAsync(global::Compassiot.Compass.V1.PartialVehicleMetadataJSON request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertPartialVehicleMetadataJSONAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InsertPartialVehicleMetadataJSONAsync(global::Compassiot.Compass.V1.PartialVehicleMetadataJSON request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPartialVehicleMetadataJSON, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsert(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsert(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BatchInsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertAsync(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertAsync(global::Compass.Harvest.V1alpha1.BatchInsertRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BatchInsert, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsertCompat(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertCompat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Compass.Harvest.V1alpha1.BatchInsertResponse BatchInsertCompat(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BatchInsertCompat, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertCompatAsync(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchInsertCompatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Compass.Harvest.V1alpha1.BatchInsertResponse> BatchInsertCompatAsync(global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BatchInsertCompat, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override IngestServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IngestServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(IngestServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Insert, serviceImpl.Insert)
          .AddMethod(__Method_InsertCompat, serviceImpl.InsertCompat)
          .AddMethod(__Method_InsertPartialLatLng, serviceImpl.InsertPartialLatLng)
          .AddMethod(__Method_InsertPartialSpeed, serviceImpl.InsertPartialSpeed)
          .AddMethod(__Method_InsertPartialEventAcceleration, serviceImpl.InsertPartialEventAcceleration)
          .AddMethod(__Method_InsertPartialEventGyro, serviceImpl.InsertPartialEventGyro)
          .AddMethod(__Method_InsertPartialEventOdo, serviceImpl.InsertPartialEventOdo)
          .AddMethod(__Method_InsertPartialEventFuelOrCharge, serviceImpl.InsertPartialEventFuelOrCharge)
          .AddMethod(__Method_InsertPartialEventMetadataKV, serviceImpl.InsertPartialEventMetadataKV)
          .AddMethod(__Method_InsertPartialEventMetadataJSON, serviceImpl.InsertPartialEventMetadataJSON)
          .AddMethod(__Method_InsertPartialVehicleMetadataKV, serviceImpl.InsertPartialVehicleMetadataKV)
          .AddMethod(__Method_InsertPartialVehicleMetadataJSON, serviceImpl.InsertPartialVehicleMetadataJSON)
          .AddMethod(__Method_BatchInsert, serviceImpl.BatchInsert)
          .AddMethod(__Method_BatchInsertCompat, serviceImpl.BatchInsertCompat).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, IngestServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Insert, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PositionEvent, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.Insert));
      serviceBinder.AddMethod(__Method_InsertCompat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compass.Harvest.V1alpha1.PositionEventCompat, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertCompat));
      serviceBinder.AddMethod(__Method_InsertPartialLatLng, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventLatLng, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialLatLng));
      serviceBinder.AddMethod(__Method_InsertPartialSpeed, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventSpeed, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialSpeed));
      serviceBinder.AddMethod(__Method_InsertPartialEventAcceleration, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventAcceleration, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialEventAcceleration));
      serviceBinder.AddMethod(__Method_InsertPartialEventGyro, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventGyro, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialEventGyro));
      serviceBinder.AddMethod(__Method_InsertPartialEventOdo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventOdo, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialEventOdo));
      serviceBinder.AddMethod(__Method_InsertPartialEventFuelOrCharge, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventFuelOrCharge, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialEventFuelOrCharge));
      serviceBinder.AddMethod(__Method_InsertPartialEventMetadataKV, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventMetadataKV, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialEventMetadataKV));
      serviceBinder.AddMethod(__Method_InsertPartialEventMetadataJSON, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialEventMetadataJSON, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialEventMetadataJSON));
      serviceBinder.AddMethod(__Method_InsertPartialVehicleMetadataKV, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialVehicleMetadataKV, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialVehicleMetadataKV));
      serviceBinder.AddMethod(__Method_InsertPartialVehicleMetadataJSON, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compassiot.Compass.V1.PartialVehicleMetadataJSON, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.InsertPartialVehicleMetadataJSON));
      serviceBinder.AddMethod(__Method_BatchInsert, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compass.Harvest.V1alpha1.BatchInsertRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(serviceImpl.BatchInsert));
      serviceBinder.AddMethod(__Method_BatchInsertCompat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Compass.Harvest.V1alpha1.BatchInsertCompatRequest, global::Compass.Harvest.V1alpha1.BatchInsertResponse>(serviceImpl.BatchInsertCompat));
    }

  }
}
#endregion
