// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: compass/harvest/v1alpha1/ingest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Compass.Harvest.V1Alpha1 {

  /// <summary>Holder for reflection information generated from compass/harvest/v1alpha1/ingest.proto</summary>
  public static partial class IngestReflection {

    #region Descriptor
    /// <summary>File descriptor for compass/harvest/v1alpha1/ingest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IngestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVjb21wYXNzL2hhcnZlc3QvdjFhbHBoYTEvaW5nZXN0LnByb3RvEhhjb21w",
            "YXNzLmhhcnZlc3QudjFhbHBoYTEaHGdvb2dsZS9hcGkvYW5ub3RhdGlvbnMu",
            "cHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoXZ29vZ2xlL3Jw",
            "Yy9zdGF0dXMucHJvdG8aHGNvbXBhc3MvaWFtL3Blcm1pc3Npb24ucHJvdG8a",
            "LWNvbXBhc3MvaGFydmVzdC92MWFscGhhMS9wb3NpdGlvbl9ldmVudC5wcm90",
            "byJNChJCYXRjaEluc2VydFJlcXVlc3QSNwoGZXZlbnRzGAEgAygLMicuY29t",
            "cGFzcy5oYXJ2ZXN0LnYxYWxwaGExLlBvc2l0aW9uRXZlbnQiTAoTQmF0Y2hJ",
            "bnNlcnRSZXNwb25zZRI1CgZlcnJvcnMYASADKAsyJS5jb21wYXNzLmhhcnZl",
            "c3QudjFhbHBoYTEuSW5zZXJ0RXJyb3IiPwoLSW5zZXJ0RXJyb3ISDQoFaW5k",
            "ZXgYASABKAUSIQoFZXJyb3IYAiABKAsyEi5nb29nbGUucnBjLlN0YXR1czKm",
            "EAoNSW5nZXN0U2VydmljZRKCAQoGSW5zZXJ0EicuY29tcGFzcy5oYXJ2ZXN0",
            "LnYxYWxwaGExLlBvc2l0aW9uRXZlbnQaFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkiN4K1GBgKFmNvbXBhc3MuaGFydmVzdC5pbnNlcnSC0+STAhUiEC92MWFs",
            "cGhhMS9pbmdlc3Q6ASoSogEKE0luc2VydFBhcnRpYWxMYXRMbmcSLC5jb21w",
            "YXNzLmhhcnZlc3QudjFhbHBoYTEuUGFydGlhbEV2ZW50TGF0TG5nGhYuZ29v",
            "Z2xlLnByb3RvYnVmLkVtcHR5IkWCtRgYChZjb21wYXNzLmhhcnZlc3QuaW5z",
            "ZXJ0gtPkkwIjIh4vdjFhbHBoYTEvcGFydGlhbGluZ2VzdC9sYXRsbmc6ASoS",
            "nwEKEkluc2VydFBhcnRpYWxTcGVlZBIrLmNvbXBhc3MuaGFydmVzdC52MWFs",
            "cGhhMS5QYXJ0aWFsRXZlbnRTcGVlZBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eSJEgrUYGAoWY29tcGFzcy5oYXJ2ZXN0Lmluc2VydILT5JMCIiIdL3YxYWxw",
            "aGExL3BhcnRpYWxpbmdlc3Qvc3BlZWQ6ASoSuQEKHkluc2VydFBhcnRpYWxF",
            "dmVudEFjY2VsZXJhdGlvbhIyLmNvbXBhc3MuaGFydmVzdC52MWFscGhhMS5Q",
            "YXJ0aWFsRXZlbnRBY2NlbGVyYXRpb24aFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkiS4K1GBgKFmNvbXBhc3MuaGFydmVzdC5pbnNlcnSC0+STAikiJC92MWFs",
            "cGhhMS9wYXJ0aWFsaW5nZXN0L2FjY2VsZXJhdGlvbjoBKhKhAQoWSW5zZXJ0",
            "UGFydGlhbEV2ZW50R3lybxIqLmNvbXBhc3MuaGFydmVzdC52MWFscGhhMS5Q",
            "YXJ0aWFsRXZlbnRHeXJvGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IkOCtRgY",
            "ChZjb21wYXNzLmhhcnZlc3QuaW5zZXJ0gtPkkwIhIhwvdjFhbHBoYTEvcGFy",
            "dGlhbGluZ2VzdC9neXJvOgEqEp4BChVJbnNlcnRQYXJ0aWFsRXZlbnRPZG8S",
            "KS5jb21wYXNzLmhhcnZlc3QudjFhbHBoYTEuUGFydGlhbEV2ZW50T2RvGhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5IkKCtRgYChZjb21wYXNzLmhhcnZlc3Qu",
            "aW5zZXJ0gtPkkwIgIhsvdjFhbHBoYTEvcGFydGlhbGluZ2VzdC9vZG86ASoS",
            "uwEKHkluc2VydFBhcnRpYWxFdmVudEZ1ZWxPckNoYXJnZRIyLmNvbXBhc3Mu",
            "aGFydmVzdC52MWFscGhhMS5QYXJ0aWFsRXZlbnRGdWVsT3JDaGFyZ2UaFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkiTYK1GBgKFmNvbXBhc3MuaGFydmVzdC5p",
            "bnNlcnSC0+STAisiJi92MWFscGhhMS9wYXJ0aWFsaW5nZXN0L2Z1ZWxfb3Jf",
            "Y2hhcmdlOgEqErMBChxJbnNlcnRQYXJ0aWFsRXZlbnRNZXRhZGF0YUtWEjAu",
            "Y29tcGFzcy5oYXJ2ZXN0LnYxYWxwaGExLlBhcnRpYWxFdmVudE1ldGFkYXRh",
            "S1YaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiSYK1GBgKFmNvbXBhc3MuaGFy",
            "dmVzdC5pbnNlcnSC0+STAiciIi92MWFscGhhMS9wYXJ0aWFsaW5nZXN0L21l",
            "dGFkYXRha3Y6ASoSuQEKHkluc2VydFBhcnRpYWxFdmVudE1ldGFkYXRhSlNP",
            "ThIyLmNvbXBhc3MuaGFydmVzdC52MWFscGhhMS5QYXJ0aWFsRXZlbnRNZXRh",
            "ZGF0YUpTT04aFi5nb29nbGUucHJvdG9idWYuRW1wdHkiS4K1GBgKFmNvbXBh",
            "c3MuaGFydmVzdC5pbnNlcnSC0+STAikiJC92MWFscGhhMS9wYXJ0aWFsaW5n",
            "ZXN0L21ldGFkYXRhanNvbjoBKhKxAQoeSW5zZXJ0UGFydGlhbFZlaGljbGVN",
            "ZXRhZGF0YUtWEjIuY29tcGFzcy5oYXJ2ZXN0LnYxYWxwaGExLlBhcnRpYWxW",
            "ZWhpY2xlTWV0YWRhdGFLVhoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSJDgrUY",
            "GAoWY29tcGFzcy5oYXJ2ZXN0Lmluc2VydILT5JMCISIcL3YxYWxwaGExL3Zl",
            "aGljbGUvbWV0YWRhdGFrdjoBKhK3AQogSW5zZXJ0UGFydGlhbFZlaGljbGVN",
            "ZXRhZGF0YUpTT04SNC5jb21wYXNzLmhhcnZlc3QudjFhbHBoYTEuUGFydGlh",
            "bFZlaGljbGVNZXRhZGF0YUpTT04aFi5nb29nbGUucHJvdG9idWYuRW1wdHki",
            "RYK1GBgKFmNvbXBhc3MuaGFydmVzdC5pbnNlcnSC0+STAiMiHi92MWFscGhh",
            "MS92ZWhpY2xlL21ldGFkYXRhanNvbjoBKhKpAQoLQmF0Y2hJbnNlcnQSLC5j",
            "b21wYXNzLmhhcnZlc3QudjFhbHBoYTEuQmF0Y2hJbnNlcnRSZXF1ZXN0Gi0u",
            "Y29tcGFzcy5oYXJ2ZXN0LnYxYWxwaGExLkJhdGNoSW5zZXJ0UmVzcG9uc2Ui",
            "PYK1GBgKFmNvbXBhc3MuaGFydmVzdC5pbnNlcnSC0+STAhsiFi92MWFscGhh",
            "MS9pbmdlc3Q6YmF0Y2g6ASpCSFpGdjIuY29tcGFzcy5pb3QvZ2VucHJvdG8v",
            "Y29tcGFzc2FwaXMvY29tcGFzcy9oYXJ2ZXN0L3YxYWxwaGExO2hhcnZlc3Rw",
            "YmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Rpc.StatusReflection.Descriptor, global::Compass.Iam.PermissionReflection.Descriptor, global::Compass.Harvest.V1Alpha1.PositionEventReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Compass.Harvest.V1Alpha1.BatchInsertRequest), global::Compass.Harvest.V1Alpha1.BatchInsertRequest.Parser, new[]{ "Events" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Compass.Harvest.V1Alpha1.BatchInsertResponse), global::Compass.Harvest.V1Alpha1.BatchInsertResponse.Parser, new[]{ "Errors" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Compass.Harvest.V1Alpha1.InsertError), global::Compass.Harvest.V1Alpha1.InsertError.Parser, new[]{ "Index", "Error" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// Batch request for sending multiple events in a single call
  /// please don't go crazy on the message size !
  /// </summary>
  public sealed partial class BatchInsertRequest : pb::IMessage<BatchInsertRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchInsertRequest> _parser = new pb::MessageParser<BatchInsertRequest>(() => new BatchInsertRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BatchInsertRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Compass.Harvest.V1Alpha1.IngestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchInsertRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchInsertRequest(BatchInsertRequest other) : this() {
      events_ = other.events_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchInsertRequest Clone() {
      return new BatchInsertRequest(this);
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Compass.Harvest.V1Alpha1.PositionEvent> _repeated_events_codec
        = pb::FieldCodec.ForMessage(10, global::Compass.Harvest.V1Alpha1.PositionEvent.Parser);
    private readonly pbc::RepeatedField<global::Compass.Harvest.V1Alpha1.PositionEvent> events_ = new pbc::RepeatedField<global::Compass.Harvest.V1Alpha1.PositionEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Compass.Harvest.V1Alpha1.PositionEvent> Events {
      get { return events_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BatchInsertRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BatchInsertRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!events_.Equals(other.events_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= events_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      events_.WriteTo(output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      events_.WriteTo(ref output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += events_.CalculateSize(_repeated_events_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BatchInsertRequest other) {
      if (other == null) {
        return;
      }
      events_.Add(other.events_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            events_.AddEntriesFrom(ref input, _repeated_events_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// List of errors ordered according to the BatchInsertRequest
  /// </summary>
  public sealed partial class BatchInsertResponse : pb::IMessage<BatchInsertResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BatchInsertResponse> _parser = new pb::MessageParser<BatchInsertResponse>(() => new BatchInsertResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BatchInsertResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Compass.Harvest.V1Alpha1.IngestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchInsertResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchInsertResponse(BatchInsertResponse other) : this() {
      errors_ = other.errors_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BatchInsertResponse Clone() {
      return new BatchInsertResponse(this);
    }

    /// <summary>Field number for the "errors" field.</summary>
    public const int ErrorsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Compass.Harvest.V1Alpha1.InsertError> _repeated_errors_codec
        = pb::FieldCodec.ForMessage(10, global::Compass.Harvest.V1Alpha1.InsertError.Parser);
    private readonly pbc::RepeatedField<global::Compass.Harvest.V1Alpha1.InsertError> errors_ = new pbc::RepeatedField<global::Compass.Harvest.V1Alpha1.InsertError>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Compass.Harvest.V1Alpha1.InsertError> Errors {
      get { return errors_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BatchInsertResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BatchInsertResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!errors_.Equals(other.errors_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= errors_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      errors_.WriteTo(output, _repeated_errors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      errors_.WriteTo(ref output, _repeated_errors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += errors_.CalculateSize(_repeated_errors_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BatchInsertResponse other) {
      if (other == null) {
        return;
      }
      errors_.Add(other.errors_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            errors_.AddEntriesFrom(input, _repeated_errors_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            errors_.AddEntriesFrom(ref input, _repeated_errors_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///
  /// e.g. if BatchInsertRequest.events[2] contains an error
  /// BatchInsertResponse.errors.index = 2 should contain the relevant message
  /// </summary>
  public sealed partial class InsertError : pb::IMessage<InsertError>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InsertError> _parser = new pb::MessageParser<InsertError>(() => new InsertError());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InsertError> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Compass.Harvest.V1Alpha1.IngestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InsertError() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InsertError(InsertError other) : this() {
      index_ = other.index_;
      error_ = other.error_ != null ? other.error_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InsertError Clone() {
      return new InsertError(this);
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 1;
    private int index_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private global::Google.Rpc.Status error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Rpc.Status Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InsertError);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InsertError other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Index != other.Index) return false;
      if (!object.Equals(Error, other.Error)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Index != 0) hash ^= Index.GetHashCode();
      if (error_ != null) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Index != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Index);
      }
      if (error_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Index != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Index);
      }
      if (error_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
      }
      if (error_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InsertError other) {
      if (other == null) {
        return;
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      if (other.error_ != null) {
        if (error_ == null) {
          Error = new global::Google.Rpc.Status();
        }
        Error.MergeFrom(other.Error);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Index = input.ReadInt32();
            break;
          }
          case 18: {
            if (error_ == null) {
              Error = new global::Google.Rpc.Status();
            }
            input.ReadMessage(Error);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Index = input.ReadInt32();
            break;
          }
          case 18: {
            if (error_ == null) {
              Error = new global::Google.Rpc.Status();
            }
            input.ReadMessage(Error);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
