# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: compass/harvest/v1alpha1/harvest.proto for package 'Compass.Harvest.V1alpha1'

require 'grpc'
require 'compass/harvest/v1alpha1/harvest_pb'

module Compass
  module Harvest
    module V1alpha1
      module IngestService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'compass.harvest.v1alpha1.IngestService'

          rpc :Insert, ::Compassiot::Compass::V1::PositionEvent, ::Google::Protobuf::Empty
          rpc :InsertPartial, ::Compassiot::Compass::V1::PositionEvent, ::Google::Protobuf::Empty
          rpc :PutVehicle, ::Compassiot::Compass::V1::Vehicle, ::Google::Protobuf::Empty
          rpc :InsertCompat, ::Compass::Harvest::V1alpha1::PositionEventCompat, ::Google::Protobuf::Empty
          rpc :BatchInsert, ::Compass::Harvest::V1alpha1::BatchInsertRequest, ::Compass::Harvest::V1alpha1::BatchInsertResponse
          rpc :BatchInsertPartial, ::Compass::Harvest::V1alpha1::BatchInsertRequest, ::Compass::Harvest::V1alpha1::BatchInsertResponse
          rpc :BatchInsertCompat, ::Compass::Harvest::V1alpha1::BatchInsertCompatRequest, ::Compass::Harvest::V1alpha1::BatchInsertResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
