# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compass/harvest/v1alpha1/ingest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from compass.iam import permission_pb2 as compass_dot_iam_dot_permission__pb2
from compass.harvest.v1alpha1 import position_event_pb2 as compass_dot_harvest_dot_v1alpha1_dot_position__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%compass/harvest/v1alpha1/ingest.proto\x12\x18\x63ompass.harvest.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17google/rpc/status.proto\x1a\x1c\x63ompass/iam/permission.proto\x1a-compass/harvest/v1alpha1/position_event.proto\"M\n\x12\x42\x61tchInsertRequest\x12\x37\n\x06\x65vents\x18\x01 \x03(\x0b\x32\'.compass.harvest.v1alpha1.PositionEvent\"L\n\x13\x42\x61tchInsertResponse\x12\x35\n\x06\x65rrors\x18\x01 \x03(\x0b\x32%.compass.harvest.v1alpha1.InsertError\"?\n\x0bInsertError\x12\r\n\x05index\x18\x01 \x01(\x05\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.google.rpc.Status2\xc0\x02\n\rIngestService\x12\x82\x01\n\x06Insert\x12\'.compass.harvest.v1alpha1.PositionEvent\x1a\x16.google.protobuf.Empty\"7\x82\xb5\x18\x18\n\x16\x63ompass.harvest.insert\x82\xd3\xe4\x93\x02\x15\"\x10/v1alpha1/ingest:\x01*\x12\xa9\x01\n\x0b\x42\x61tchInsert\x12,.compass.harvest.v1alpha1.BatchInsertRequest\x1a-.compass.harvest.v1alpha1.BatchInsertResponse\"=\x82\xb5\x18\x18\n\x16\x63ompass.harvest.insert\x82\xd3\xe4\x93\x02\x1b\"\x16/v1alpha1/ingest:batch:\x01*BHZFv2.compass.iot/genproto/compassapis/compass/harvest/v1alpha1;harvestpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compass.harvest.v1alpha1.ingest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFv2.compass.iot/genproto/compassapis/compass/harvest/v1alpha1;harvestpb'
  _INGESTSERVICE.methods_by_name['Insert']._options = None
  _INGESTSERVICE.methods_by_name['Insert']._serialized_options = b'\202\265\030\030\n\026compass.harvest.insert\202\323\344\223\002\025\"\020/v1alpha1/ingest:\001*'
  _INGESTSERVICE.methods_by_name['BatchInsert']._options = None
  _INGESTSERVICE.methods_by_name['BatchInsert']._serialized_options = b'\202\265\030\030\n\026compass.harvest.insert\202\323\344\223\002\033\"\026/v1alpha1/ingest:batch:\001*'
  _BATCHINSERTREQUEST._serialized_start=228
  _BATCHINSERTREQUEST._serialized_end=305
  _BATCHINSERTRESPONSE._serialized_start=307
  _BATCHINSERTRESPONSE._serialized_end=383
  _INSERTERROR._serialized_start=385
  _INSERTERROR._serialized_end=448
  _INGESTSERVICE._serialized_start=451
  _INGESTSERVICE._serialized_end=771
# @@protoc_insertion_point(module_scope)
