# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compass/harvest/v1alpha1/position_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from compass.type.geo import geo_pb2 as compass_dot_type_dot_geo_dot_geo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-compass/harvest/v1alpha1/position_event.proto\x12\x18\x63ompass.harvest.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1a\x63ompass/type/geo/geo.proto\"T\n\x08Position\x12(\n\x06latlng\x18\x01 \x01(\x0b\x32\x18.compass.type.geo.LatLng\x12\r\n\x05speed\x18\x02 \x01(\x01\x12\x0f\n\x07\x62\x65\x61ring\x18\x03 \x01(\x01\"/\n\x0c\x41\x63\x63\x65leration\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"0\n\x04Gyro\x12\x0c\n\x04roll\x18\x01 \x01(\x01\x12\r\n\x05pitch\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x01\"\xf7\x03\n\rPositionEvent\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12?\n\x0etransport_type\x18\x03 \x01(\x0e\x32\'.compass.harvest.v1alpha1.TransportType\x12;\n\x0cvehicle_type\x18\x04 \x01(\x0e\x32%.compass.harvest.v1alpha1.VehicleType\x12\x34\n\x08position\x18\x05 \x01(\x0b\x32\".compass.harvest.v1alpha1.Position\x12<\n\x0c\x61\x63\x63\x65leration\x18\x07 \x01(\x0b\x32&.compass.harvest.v1alpha1.Acceleration\x12,\n\x04gyro\x18\x08 \x01(\x0b\x32\x1e.compass.harvest.v1alpha1.Gyro\x12\x0f\n\x07trip_id\x18\t \x01(\t\x12\x43\n\x06labels\x18\x06 \x03(\x0b\x32\x33.compass.harvest.v1alpha1.PositionEvent.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*H\n\rTransportType\x12\x1e\n\x1aTRANSPORT_TYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PRIVATE\x10\x01\x12\n\n\x06PUBLIC\x10\x02*Q\n\x0bVehicleType\x12\x1c\n\x18VEHICLE_TYPE_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42US\x10\x01\x12\x07\n\x03\x43\x41R\x10\x02\x12\x07\n\x03VAN\x10\x03\x12\t\n\x05TRUCK\x10\x04\x42HZFv2.compass.iot/genproto/compassapis/compass/harvest/v1alpha1;harvestpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compass.harvest.v1alpha1.position_event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZFv2.compass.iot/genproto/compassapis/compass/harvest/v1alpha1;harvestpb'
  _POSITIONEVENT_LABELSENTRY._options = None
  _POSITIONEVENT_LABELSENTRY._serialized_options = b'8\001'
  _TRANSPORTTYPE._serialized_start=827
  _TRANSPORTTYPE._serialized_end=899
  _VEHICLETYPE._serialized_start=901
  _VEHICLETYPE._serialized_end=982
  _POSITION._serialized_start=136
  _POSITION._serialized_end=220
  _ACCELERATION._serialized_start=222
  _ACCELERATION._serialized_end=269
  _GYRO._serialized_start=271
  _GYRO._serialized_end=319
  _POSITIONEVENT._serialized_start=322
  _POSITIONEVENT._serialized_end=825
  _POSITIONEVENT_LABELSENTRY._serialized_start=780
  _POSITIONEVENT_LABELSENTRY._serialized_end=825
# @@protoc_insertion_point(module_scope)
