# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compass/type/geo/geo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ompass/type/geo/geo.proto\x12\x10\x63ompass.type.geo\"-\n\x06LatLng\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"/\n\x08LatLng32\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"o\n\x0b\x42oundingBox\x12/\n\rnorth_eastern\x18\x01 \x01(\x0b\x32\x18.compass.type.geo.LatLng\x12/\n\rsouth_western\x18\x02 \x01(\x0b\x32\x18.compass.type.geo.LatLng\"0\n\x04Path\x12(\n\x06points\x18\x01 \x03(\x0b\x32\x18.compass.type.geo.LatLng\"4\n\x06Region\x12*\n\x06points\x18\x01 \x03(\x0b\x32\x1a.compass.type.geo.LatLng32B<Z:v2.compass.iot/genproto/compassapis/compass/type/geo;geopbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compass.type.geo.geo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:v2.compass.iot/genproto/compassapis/compass/type/geo;geopb'
  _LATLNG._serialized_start=48
  _LATLNG._serialized_end=93
  _LATLNG32._serialized_start=95
  _LATLNG32._serialized_end=142
  _BOUNDINGBOX._serialized_start=144
  _BOUNDINGBOX._serialized_end=255
  _PATH._serialized_start=257
  _PATH._serialized_end=305
  _REGION._serialized_start=307
  _REGION._serialized_end=359
# @@protoc_insertion_point(module_scope)
